services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auctions
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

  server:
    build: ./apps/server
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/auctions
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    ports:
      - '4000:4000'

  client:
    build: ./apps/client
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - server
    ports:
      - '3000:3000'

volumes:
  db_data: 