name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: auctions
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint client
        run: pnpm --filter ./apps/client lint
      - name: Lint server
        run: pnpm --filter ./apps/server lint
      - name: Build client
        run: pnpm --filter ./apps/client build
      - name: Build server
        run: pnpm --filter ./apps/server build
      - name: Test client
        run: pnpm --filter ./apps/client test || true
      - name: Test server
        run: pnpm --filter ./apps/server test || true 